name: Cover
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  your_job_name:
    runs-on: windows-latest
    env:
      PATH: C:\Abdul
      JVM_ARGS: -Xmx4096m
    steps:
    - name: Check Path
      run: echo $env:PATH
    - name: Add Git to PATH
      run: |
        echo 'C:\Program Files\Git\bin' >> $GITHUB_PATH

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: Abdul7777K/DemoProject
        ref: main
    - name: Initialize Gradle build
      run: gradle init
    - name: Compile project
      run: gradle build --scan
    - name: Download Diffblue Cover
      run: |
        mkdir C:\demo\dcover
        cd C:\demo\dcover
        curl --silent --show-error --location --output "diffblue-cover-cli.zip" "https://release.diffblue.com/2023.10.01/88bd072f1e783483a53e1fa7e53511d57b64a3b64e6f618c624f5a990409262f/diffblue-cover-cli-2023.10.01.zip"
    - name: List contents of dcover directory
      run: |
        dir C:\demo\dcover
