name: Cover
on:
  # Allow the workflow to be triggered manually using the GitHub API, CLI, or browser interface
  workflow_dispatch:
  # Trigger the workflow automatically on pushes to main
  push:
    branches: [ main ]
jobs:
  your_job_name:
    runs-on: windows-latest

    env:
      PATH: C:\Abdul
      JVM_ARGS: -Xmx4096m
    steps:
    - name: Check Path
      run: echo $env:PATH
