name: Cover
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  your_job_name:
    runs-on: windows-latest
    env:
      JVM_ARGS: -Xmx4096m
    steps:
    - name: set env name
      uses: myci-actions/append-to-path-windows@2
      with:
        path: D:\a\DemoProject\DemoProject\demo\dcover
        env-var: PATH
    - name: Check Path
      run: echo $env:PATH
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: Abdul7777K/DemoProject
        ref: main
    - name: Initialize Gradle build
      run: gradle init

    - name: Compile project
      run: gradle build --scan

    # Get, unzip, and activate Diffblue Cover
    - name: Download Diffblue Cover
      run: |
        mkdir demo/dcover
    - name: Redownload Diffblue Cover CLI zip files
      run: |
        curl --silent --show-error --location --output "diffblue-cover-cli.zip" "https://release.diffblue.com/2023.10.01/88bd072f1e783483a53e1fa7e53511d57b64a3b64e6f618c624f5a990409262f/diffblue-cover-cli-2023.10.01.zip"
    - name: Print the list of dir
      run: |
        ls
        pwd
    - name: Unzip Diffblue Cover CLI zip file
      run: |
        unzip diffblue-cover-cli.zip -d demo/dcover
        ls demo/dcover
       
    - name: Activate
      run: |
         $env:Path
         dcover activate "${{ secrets.DIFFBLUE_COVER_LICENSE_KEY }}"
      working-directory: D:\a\DemoProject\DemoProject\demo\dcover
