name: Cover
on:
  # Allow the workflow to be triggered manually using the GitHub API, CLI, or browser interface
  workflow_dispatch:
  # Trigger the workflow automatically on pushes to main
  push:
    branches: [ main ]
jobs:
  your_job_name:
    runs-on: windows-latest

    env:
      PATH: C:\Abdul
      JVM_ARGS: -Xmx4096m
    steps:
    - name: Check Path
      run: echo $env:PATH
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Initialize Gradle build
      run: gradle init
    - name: Compile project
      run: gradle build --scan
    # Get, unzip, and activate Diffblue Cover
    - name: Download Diffblue Cover
      run: |
        mkdir demo/dcover

        cd demo/dcover

    - name: Redownload Diffblue Cover CLI zip files
      run: |
        curl --silent --show-error --location --output "diffblue-cover-cli.zip" "https://release.diffblue.com/2023.10.01/88bd072f1e783483a53e1fa7e53511d57b64a3b64e6f618c624f5a990409262f/diffblue-cover-cli-2023.10.01.zip"
    - name: Print the list of dir
      run: |
        ls
